modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

issueTrackerURL = "https://github.com/AbdElAziz333/Saturn/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://github.com/AbdElAziz333/Saturn/raw/mc1.20.1/dev/updates.json"
displayURL = "https://modrinth.com/mod/saturn"
logoFile = "logo.png"
credits = "${mod_authors}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"