modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPL-3.0-only"

issueTrackerURL = "https://github.com/AbdElAziz333/Saturn/issues"

[[mods]]
modId = "saturn"
version = "${file.jarVersion}"
displayName = "Saturn"
updateJSONURL="https://github.com/AbdElAziz333/Saturn/raw/mc1.19.2/dev/updates.json"
displayURL = "https://legacy.curseforge.com/minecraft/mc-mods/saturn"
logoFile = "logo.png"
credits="AbdElAziz"
authors="AbdElAziz"
description = '''
A performance mod designed to optimize Minecraft's memory usage.
'''

[[dependencies.saturn]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.saturn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"