modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-3.0-only"

issueTrackerURL = "https://github.com/AbdElAziz333/Saturn/issues"

[[mods]]
modId = "saturn"
version = "${version}"
displayName = "Saturn"
# updateJSONURL="https://changeme.dev/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/saturn"
logoFile = "logo.png"
credits="AbdElAziz"
authors="AbdElAziz"
description = '''
A performance mod designed to optimize Minecraft's memory usage
'''

[[dependencies.saturn]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.saturn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"